### ISSUE TITLE
Is there an option to disable climate control on Wattio?

### ISSUE THREAD

**Issue by azaceta** [dmoranf/home-assistant-wattio#1]
I've replace my wattio therm with a Nest, as Wattio is not modulant neither Opentherm, which I needed. But I've kept 1 pod plus the energy meters.
Not sure if I will keep it all, but meanwhile, I've got 2 thermostat in Home Assistant.
Is there an option, like with `security: false` to disable the climate control? If not, it would be a nice addition.

Thx!

**Comment by dmoranf** [comment]
You can now avoid adding a sensor to hass using the sensor_exclude option in configuration.yaml.

Just specify device's IEEE in list format and in lowercase (you can find it in Wattio's APP inside the device, Advanced tab) :

sensor_exclude: ["ieee1", "ieee2"]

**Comment by azaceta** [comment]
Sounds nice, but I've installed the latest version, added the sensor_exclude clause, and the HA server still shows Wattio's climate entity. Do I need to delete or reset any part of the initial installation?

**Comment by dmoranf** [comment]
Mmm it shouldn't be necessary doing anything else ... does it make any difference if you write the ieee full in lower case or full in upper case?

If the component excludes a sensor it writes an error message to hass logs just to show why is not adding the device ... Do you have any kind of entry in your hass log?

Regards!

**Comment by dmoranf** [comment]
Mmm it shouldn't be necessary doing anything else ... does it make any difference if you write the ieee full in lower case or full in upper case?

If the component excludes a sensor it writes an error message to hass logs just to show why is not adding the device ... Do you have any kind of entry in your hass log?

Regards!

**Comment by dmoranf** [comment]
Mmm it shouldn't be necessary doing anything else ... does it make any difference if you write the ieee full in lower case or full in upper case?

If the component excludes a sensor it writes an error message to hass logs just to show why is not adding the device ... Do you have any kind of entry in your hass log?

Regards!

**Comment by azaceta** [comment]
Using lowercase in the IEEE id solved it!
Climate entity is gone as needed.
Thanks a lot!
