### ISSUE TITLE
Soporte para Wattio Air y offsets para sensores

### ISSUE THREAD

**Issue by garzy** [dmoranf/home-assistant-wattio#11]
Buenas tardes, 

¿podría añadir soporte para el wattio air y así poder controlar los aparatos de aire acondicionado? 

Gracias!

**Comment by dmoranf** [comment]
Hola!

He estado revisando la documentación y no tienen nada referente al Wattio Air, no sé si es porque salió después o porque no lo soportan.

Si ya tienes el plugin funcionando podemos hacer una prueba rápida con postman para ver si la API devuelve datos de tu Wattio AIR e intentar implementarlo en el plugin.

Tienes que utilizar el token de acceso que tendrás ya en wattio.conf en la carpeta de instalación de Home Assistant:

Descarga postman gratis de www.postman.com

Habría que hacer una petición GET a https://api.wattio.com/public/v1/appliances/status formateada de la siguiente manera:

<img width="946" alt="image" src="https://user-images.githubusercontent.com/7201665/120153085-96b8c200-c1ee-11eb-9d7a-750d28258f0f.png">

Unicamente tienes que poner el Authentication type a Bearer Token y poner el token que has copiado del wattio.conf.

Eso debería devolverte el estado de todos tus appliances, mira a ver si te sale ahi el Wattio Air ...

Si lo ves complicado, puedo pedirle a soporte directamente que me den info para intentar implementarlo :)

**Comment by garzy** [comment]
Gracias por la info, he realizado la petición y no aparece el Air por ningún lado en la respuesta (aparecen siren, bat, therm y door, que son los que tengo)

El dispositivo AIR, efectivamente, salió bastante más tarde, y me da que tienen implementado lo justo...

¿Qué hacemos? ¿Escribo un mensaje a soporte preguntando?

Otra cosa..... ¿Sobre wattio cam tienes algo? aunque ésto no me preocupa mucho, su cámara es cerrada y dudo mucho que se pueda hacer algo.

Vamos hablando, cualquier cosa, estoy aquí para cacharrear y ayudar.

Gracias por tu excelente trabajo, hacía tiempo que soñaba con este componente y lo has llevado a cabo!! Enhorabuena!

**Comment by dmoranf** [comment]
Buenas!

Le escribo a soporte preguntando y te cuento, la verdad que no tengo muchas esperanzas, la API la publicaron después de varias peticiones en el foro hace años, parece que lo hicieron un poco a la carrera, la implementación de los dispositivos de seguridad es totalmente diferente a la de los otros dispositivos y no la han tocado desde entonces, da la sensación que el proyecto en general quedó un poco parado hace tiempo ..

Sobre la CAM, oficialmente tampoco hay "acceso" externo, aprovecho para preguntarles también. La verdad que no investigué mucho al respecto porque la mía lleva años en el cajón, (un producto que implementaron de aquella manera en la solución), pero al final es una JIMI JH08 a la que le han modificado un poco el software y supongo que el firmware aunque no lo tengo claro ... me apunto conectarla y echarle un ojo a ver si se le puede atacar desde la LAN de alguna manera.

Mirando la docu del AIR veo que es ¿WIFI y no zigbee?, curioso ...

**Comment by garzy** [comment]
Estoy de acuerdo en todo lo que comentas, además, no entiendo como después de tantos años, en los que no han sacado nada nuevo, no se dignen a mejorar al menos el software y la Api rest.

Yo personalmente les pedí, por ejemplo, que se pudiese definir un offset en el consumo del BAT, porque al tener las luces philips hue, éstas siempre están consumiendo aunque estén en estado apagado, y me aparece un consumo total de 30W constantes en el circuito de iluminación, con las luces apagadas, me gustaría poder definir un offset para que el consumo me salga como 0W hasta que encienda una luz. ¿Crees que podrías hacer ésto de alguna manera para que el sensor de consumo de BAT en Lovelace marque 0W?

Lo de la CAM es de chiste, además para emparejarla al sistema se necesita una versión de Android vieja, con las nuevas no funciona, una vez emparejada, ya sí se puede usar un Android moderno.

Sobre el AIR, efectivamente, va por wifi, o al menos para conectarlo te pide el típico paso de configurar a qué red 2.5G conectarse, y le tienes que poner el SSID y la pass, así que si, supongo que no lleva nada de Zigbee.

Sin duda, creo que hoy existen soluciones mucho mejores, más abiertas y mejor integrables en HomeAssistant, pero después de gastarnos un dineral en todo el sistema, como que duele bastante deshacerse de ello malvendiéndolo.

**Comment by dmoranf** [comment]
Buenas!

Te miro lo del offset del BAT, en principio no veo problema en implementarlo, lo metería como una variable en la configuración del componente ... lo vemos

Yo también tengo unas HUE y la verdad no lo había pensado pero me parece buena idea :)

Un Saludo,

**Comment by dmoranf** [comment]
Gracias por contactar con soporte.

Te comento que desde la API no se puede acceder a Wattio Air y por el momento tampoco tenemos previsto desarrollarlo.

Gracias igualmente por tu consulta.

**Comment by garzy** [comment]
Vaya!, en fin, me lo esperaba, "por el momento" dicen, llevan 3 años diciendo lo mismo así que dudo que lo hagan jamás, en fin... una pena.

**Comment by dmoranf** [comment]
Pues sí, es una verdadera pena en lo que ha quedado el proyecto ... 

De cara al futuro creo que lo mejor sería intentar "migrar" los dispositivos a zigbee2mqtt y pasar del gate. Habría que generar el parser, pero tengo que hacer más pruebas con un poco más de tiempo ya que en las últimas que hice con un pod no conseguí que enlazase .... aunque debería.

Tengo ya más o menos implementado lo del offset y estoy haciendo pruebas, seguramente mañana lo pueda subir.

Saludos,

**Comment by garzy** [comment]
OK, muchas gracias por la ayuda y por las mejoras

**Comment by dmoranf** [comment]
En la versión 0.2.11 he metido el tema de los offsets, a ver si vale algo así ... la configuración sería de esta manera:

``` yaml
wattio:
      #configuracion actual ...
     sensor_offsets:[{'sensor_iee': 'ieee', 'sensor_name': 'sensor_name', 'sensor_offset': 30, 'offset_type': 1},]
```

He tenido que meter tanto ieee como nombre del sensor dado que es la única forma que hay de identificar los canales del bat, es eso o el id, pero me parece más fácil el nombre que es como está reflejado en HASS.

El offset_type puede tomar como valor 1 o 2:

- 1 -> Solo aplica el offset si el valor de consumo es ==, es decir, si pones como offset de 30, solo lo aplica cuando el sensor reporte un consumo de 30, si este es diferente, se devuelve el valor real.
- 2 -> Se aplica el offset si el valor del consumo es >= que el offset, es decir siempre que sea 30 (pj) o mayor se restaría el valor ...

Igual está un poco enrevesado el tema, estoy abierto a otras propuestas :)

Prueba y me dices

**Comment by garzy** [comment]
Sí, es un poco lío lo del offset_type, en mi caso me interesa el tipo 2 claro, aunque realmente yo lo que quiero es que siempre reste el offset, sin tener en cuenta ninguna condición, pero bueno, con el 2 me valdría sabiendo que tengo un consumo de luces constante de 30 o más.

Sobre el offset_type 1 no se yo si funcionará, por lo que dices el valor real tiene que tomar exactamente ese valor, y dudo mucho que sirva ya que la medida de energía va fluctuando (28, 29, 30, 32w, etc).

Imaginemos entonces, que tengo un offset de 30w y el consumo en ese momento es de 28.

* Con el type 1: el resultado sería de 28w
* Con el type 2: el resultado sería de 28w
* Con lo que quiero yo: el resultado sería de -2w (28 - 30), pero lo deseable sería claramente establecer el valor 0w cuando la resta salga negativa.

Imaginemos un offset de 30w y consumo real de 31w:
 * con el type1: el resultado sería de 31
 * con el type2: el resultado sería de 1w
En este caso con el type2 funcionaría como quiero, pero como hemos visto en el apartado anterior, para casos en los que sea menor el consumo que el offset no me estaría ayudando el valor.


### Resumiendo xD

Yo creo que simplemente habría que dejarse de tipos y hacer la fórmula:

`valor_real - offset`, 

y si sale negativo, establecer un 0 como resultado.

**Comment by garzy** [comment]
Por cierto, lo probaré a última hora del día, mañana te digo!

**Comment by dmoranf** [comment]
Tienes razón ... mucho más fácil !!!! Lo modifico para la 0.2.12 por si prefieres esperar ... a lo largo del día la intento subir.

**Comment by garzy** [comment]
está bien, esperamos entonces, pero sin prisa! de verdad, cuando puedas, no hay problema

**Comment by dmoranf** [comment]
Ya está subida la versión sin el lío de los types :) prueba cuando puedas y lo vemos.

Saludos!

**Comment by garzy** [comment]
Buenas, he estado probando, siguiendo los ejemplos, eliminando algunas comas sobrantes del json de ejemplo, y estableciendo el valor correcto de ieee del bat, valor que recibo en la petición JSON que me explistate al inicio de esta issue.

No consigo que funcione, en el momento que pongo el atributo 'sensor_offsets' dejan dibujarse todas las entidades del bat en el interfaz gráfico.

No sé que puede estar pasando, **aclaro que tengo 2 bat** ¿puede ser por eso? cada uno tiene un ieee distinto y me he asegurado de estar indicando el correcto.

Por favor, ¿puedes probar tú con tu bat y si funciona poner un ejemplo real de cómo se configura?

Gracias!

**Comment by dmoranf** [comment]
Hola,

Yo lo tengo así con la versión 0.2.12 (tengo un offset alto para probar que funciona):

```yaml
wattio:
     scan_interval: 60
     security: True
     security_interval: 60
     sensor_offsets: [{"sensor_ieee" : "IEEE", "sensor_name" : "Iluminación", "sensor_offset" : 200}]
```
Que tengas varios BAT no influye porque como dices cada uno tiene su IEE y por tanto es independiente

**Comment by garzy** [comment]
Adcabo de ponerlo como tú, todo en una línea, además que mi sensor también se llama "Iluminación", y está funcionando bien!!

Desconozco si tendría algúna errata en mi configuración, la cuestión es que funciona!!

Está genial gracias!!, llevo varios años esperando esta mejora por parte de Wattio ¿acaso trabajan algo en estos momentos? lo dudo xD

**Comment by dmoranf** [comment]
Fallo mío en la docu, cuando es multilinea hay que poner el > para que lo pille ...

```yaml

  sensor_offsets: >
    [
      {
        'sensor_iee': 'ieee',
        'sensor_name': 'sensor_name',
        'sensor_offset': 30,
      },
    ]

```

Cierro este issue
