### ISSUE TITLE
Sin notificación para configurar

### ISSUE THREAD

**Issue by cyberdie** [dmoranf/home-assistant-wattio#7]
Hola, tenía configurado wattio de forma manual y me he pasado a la integración por HACS borrando previamente el fichero wattio.conf para empezar de cero.
El caso es que una vez instalado y reiniciado el docker (sobre Rpi) no me aparece ninguna notificación en el UI para configurar client/secret....
He repetido el proceso varias veces sin éxito.
¿alguna idea?

**Comment by dmoranf** [comment]
Hola,

La parte del registro hace varias versiones de HASS que no la pruebo, lo reviso :) (Si tienes copia del wattio.conf te vale el anterior para la versión de HACS).

**Comment by cyberdie** [comment]
Gracias @dmoranf !
El caso es que dejando el fichero en su sitio no me aparecía ni dispositivo ni entidades por eso he empezado de cero.
Por cierto, tengo la versión 2021.4.4

**Comment by cyberdie** [comment]
Puede estar relacionado con este otro issue #8

**Comment by dmoranf** [comment]
Duplicate of #8
