### ISSUE TITLE
'ApiConfig' object has no attribute 'base_url' error configurando

### ISSUE THREAD

**Issue by cyberdie** [dmoranf/home-assistant-wattio#8]
Instalando manulmente me sale este error despues de modificar el wattio.conf.
Creo que tiene que ver con el valor base_url del configuration.yaml que está deprecated hace varias versiones.
[https://developers.home-assistant.io/blog/2020/05/08/instance-url-helper/]
Probablemente relacionado con https://github.com/dmoranf/home-assistant-wattio/blob/071b8bb9ac085dfb6a7a4bd4ecb5b634cf6ee4d2/custom_components/wattio/__init__.py#L197 

`Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/wattio/__init__.py:282
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 18:13:27 (1 occurrences)
Last logged: 18:13:27

[2882658016] 'ApiConfig' object has no attribute 'base_url'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 143, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1515, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/configurator/__init__.py", line 228, in async_handle_service_call
    await self.hass.async_add_job(callback, call.data.get(ATTR_FIELDS, {}))
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wattio/__init__.py", line 233, in wattio_configuration_callback
    setup(hass, config)
  File "/config/custom_components/wattio/__init__.py", line 196, in setup
    auth_uri = get_auth_uri(hass, config_file.get("client_id"))
  File "/config/custom_components/wattio/__init__.py", line 282, in get_auth_uri
    redirect_uri = "{}{}".format(hass.config.api.base_url, WATTIO_AUTH_START)
AttributeError: 'ApiConfig' object has no attribute 'base_url'`

**Comment by dmoranf** [comment]
Hola!
Efectivamente, parece que es eso, muchas gracias por buscar el problema :)

He publicado una versión nueva en hacs(0.2.9) cambiando únicamente el tema de las URLs y aunque el comportamiento de las ventanas de notificación es un poco errático, la ventana de finalizar no se llega a cerrar del todo ... (tengo que revisarlo con calma), he conseguido finalizar el proceso de autorización correctamente.

Pruébalo y me dices.

Saludos!

**Comment by cyberdie** [comment]
He probado desde HACS tanto teniendo el wattio.conf (con las credenciales) como no teniendo el fichero y en ambos casos no me aparecen las notificaciones de configuración ni las entidades :-( (respectivamente).
Es curioso que teniendo la integración instalada, al arrancar el docker, no me sale un warning de estos que haga referencia a WATTIO. Salen varios de otros custom_components pero no el de wattio...
`2021-04-15 15:23:54 WARNING (MainThread) [homeassistant.loader] You are using a custom integration XXXXXX which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant`

Es como si HA no "viera" el componente...
Sin embargo los ficheros están en su sitio y la integración aparece en la consola de HACS.

**Comment by dmoranf** [comment]
Si lo ficheros está en su sitio y no lo ves activo en el log al arrancar, ¿es posible que te falte la parte del configuration.yaml o que no esté bien (en este caso daría un error entiendo)? 

Si tienes el fichero viejo de wattio.conf mantenlo así no tienes que validar otra vez, y nos saltamos la validación, si no es así, pásame el logo a ver que vemos.

**Comment by cyberdie** [comment]
Pero ¿cuando instalas con HACS es necesario meter los parámetros en el configuration.yaml a mano?
Si no los metes no toman valores por defecto?

**Comment by dmoranf** [comment]
Tienes, por lo menos, que activarlo con wattio: el resto de cosas si no las pone usará los valores por defecto.

De momento la versión de HACS funciona igual que la anterior en ese aspecto, tengo que revisar si se puede activar desde hacs directamente.
