### ISSUE TITLE
Error al llamar al servicio switch/turn_on

### ISSUE THREAD

**Issue by GMTZMU** [dmoranf/home-assistant-wattio#9]
Muy buenas compañero, primero de todo muchas gracias por el trabajo que estas realizando. Hace mucho tiempo que tengo el custom component funcionando correctamente,  hasta ahora he tenido la versión 2.3 y ningún problema, al instalar la ultima versión de HA, me he encontrado con algún error y después de actualizar el custom component a la v2.9, el error persiste.
Actualmente tengo ubuntu 20.4 + HA 2021.4.4 + wattio 2.9.
Dependiendo si es un POD o un Thermic la línea de error es diferente.
Lo he validado con la versión core de HA y tengo el mismo efecto.

Adjunto el error 

Logger: homeassistant.components.websocket_api.http.connection
Source: util/async_.py:139
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 9:43:20 (15 occurrences)
Last logged: 10:44:58

[281472466429552] I/O must be done in the executor; Use `await hass.async_add_executor_job()` at custom_components/wattio/__init__.py, line 530: api_call_response = requests.put(uri, headers=api_call_headers)
[281472530562544] I/O must be done in the executor; Use `await hass.async_add_executor_job()` at custom_components/wattio/__init__.py, line 530: api_call_response = requests.put(uri, headers=api_call_headers)
[281472530562544] I/O must be done in the executor; Use `await hass.async_add_executor_job()` at custom_components/wattio/__init__.py, line 557: api_call_response = requests.put(uri, headers=api_call_headers)
[281472530562544] I/O must be done in the executor; Use `await hass.async_add_executor_job()` at custom_components/wattio/__init__.py, line 511: api_call_response = requests.put(uri, headers=api_call_headers)
[281472475722848] I/O must be done in the executor; Use `await hass.async_add_executor_job()` at custom_components/wattio/__init__.py, line 530: api_call_response = requests.put(uri, headers=api_call_headers)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 143, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1515, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 206, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 649, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 692, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 686, in _handle_entity_call
    await result
  File "/config/custom_components/wattio/switch.py", line 78, in async_turn_on
    wattio.set_switch_status(self._ieee, "on", self._devtype)
  File "/config/custom_components/wattio/__init__.py", line 530, in set_switch_status
    api_call_response = requests.put(uri, headers=api_call_headers)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 134, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1266, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 214, in putrequest
    return _HTTPConnection.putrequest(self, method, url, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 150, in protected_loop_func
    check_loop()
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 139, in check_loop
    raise RuntimeError(
RuntimeError: I/O must be done in the executor; Use `await hass.async_add_executor_job()` at custom_components/wattio/__init__.py, line 530: api_call_response = requests.put(uri, headers=api_call_headers)

**Comment by dmoranf** [comment]
Hola,

Gracias por el reporte. Por lo que comentas parece que ha habido cambios en las últimas versiones de HA actualizo mi instalación y le echo un vistazo.

**Comment by dmoranf** [comment]
Actualmente las llamadas se hacen con el módulo de requests y las estoy migrando a aiohttp (externo a hass por compatibilidad previa) para solventar el problema de los errores de async.

Estoy haciendo algunas pruebas ya, el caso es que hoy la API va especialmente mal (también me falla la app de wattio) ... y se está haciendo algo tedioso.

**Comment by GMTZMU** [comment]
Ok. Cuando lo tengas lo validamos. Gracias. Genís MartinezEl 19 abr. 2021 15:23, dmoranf ***@***.***> escribió:

Actualmente las llamadas se hacen con el módulo de requests y las estoy migrando a aiohttp (externo a hass por compatibilidad previa) para solventar el problema de los errores de async.

Estoy haciendo algunas pruebas ya, el caso es que hoy la API va especialmente mal (también me falla la app de wattio) ... y se está haciendo algo tedioso.

**Comment by GMTZMU** [comment]
Buenos días, ¿has podido avanzar?

**Comment by dmoranf** [comment]
Hola!

Disculpa, no he tenido mucho tiempo esta semana pero llevo unos días probándolo y parece que va bien, quiero hacer unas últimas pruebas, espero publicar la nueva versión a principios de esta semana.

Saludos!

**Comment by dmoranf** [comment]
Buenas,

He dejado la versión 0.2.10 en la rama devel por si quieres probarla, es con la que llevo yo probando unos días ...

Un Saludo,

**Comment by cyberdie** [comment]
Yo tengo el mismo problema.
Para probar con esa rama, ¿se puede hacer desde hacs?

**Comment by GMTZMU** [comment]
Buenas ya he instalado la ultima versión y veo lo siguiente:
POD. Funciona perfectamente, puedo encender y apagar sin problemas y no veo delay.
THERMIC. Funciona perfectamente, puedo apagar, encender, cambiar la temperatura, ponerlo en manual.
SIREN. Puedo activar y desactivar sin problemas el SIREN.
SENSORES DOOR Y MOTION. Cuando se abren o se cierra se detentan perfectamente, el MOTION detecta movimiento.

Los que no funcionan son los SWITCH.SEC_, cuando se activan o desactivan desde HASSIO, Wattio no se entera. Lo mismo pasa cuando los activas desde Wattio, HASSIO no se entera.

Muchas gracias.

**Comment by dmoranf** [comment]
@cyberdie No te sabría decir, tendría que repasarme la documentación de HACS para ver cómo se puede hacer :( No obstante, puedes pisar los ficheros de la carpeta de wattio sin más, el componente es el mismo, cuando quieras volver a la versión de HACS desde el menú de la integración de HACS le das a los 3 puntos de la parte inferior derecha, reinstalar y ya lo tienes restaurado. La vuelta atrás es sencilla.

@GMTZMU le echo un vistazo a ver que puedo ver (no tengo dispositivos de seguridad y voy un poco a ciegas), ¿Puedes ver si en el log te da algún error o algo?

Gracias!

**Comment by GMTZMU** [comment]
Buenas noches, lo he estado revisando y la integración no reporta ningún error por los SWITCH de seguridad creados. No hay eventos. Los switches encienden y apagan pero no ejecutan nada en WATTIO.

¿Es posible que se hayan creado durante una primera versión de la integración y quede como residente? 

Saludos.

Sent from Mail for Windows 10

**Comment by dmoranf** [comment]
Hola!

Pues no debería ... ¿te importaría hacer una prueba más? Activa el modo debug temporalmente para el módulo de wattio y a ver si vemos algo:

```yaml
logger:
   default: warn <-- lo que tengas puesto
   logs:
      custom_components.wattio: debug
```

¿Entiendo que pasado un rato tampoco se ve nada reflejado en wattio verdad? ¿Esto ha dejado de funcionar desde que falló el tema del set o viene de antes? La verdad que no estoy viendo nada raro en el código ... aunque me suena que había algo especial con los elementos de seguridad pero ahora mismo no recuerdo (una pena que se cargaran el foro de wattio donde lo teníamos hablado!)

Gracias!

Saludos

**Comment by cyberdie** [comment]
> @cyberdie No te sabría decir, tendría que repasarme la documentación de HACS para ver cómo se puede hacer :( No obstante, puedes pisar los ficheros de la carpeta de wattio sin más, el componente es el mismo, cuando quieras volver a la versión de HACS desde el menú de la integración de HACS le das a los 3 puntos de la parte inferior derecha, reinstalar y ya lo tienes restaurado. La vuelta atrás es sencilla.
> 
> @GMTZMU le echo un vistazo a ver que puedo ver (no tengo dispositivos de seguridad y voy un poco a ciegas), ¿Puedes ver si en el log te da algún error o algo?
> 
> Gracias!

Por mi parte, la rama devel ha hecho funcionar el thermic de nuevo. Gracias @dmoranf !!

**Comment by GMTZMU** [comment]
@dmoranf he configurado el debug de la siguiente forma:
logger:
  default: info
  logs:
    custom_components.wattio: debug
Solo he visto los siguientes mensajes.
Couldn't fetch data from WATTIO API, retrying on next scheduled update ...
22:18:59 – (ERROR) Wattio Smart Home integration - el mensaje se produjo por primera vez a las 21:10:58 y aparece 17 veces

API call Status code 500
22:18:59 – (ERROR) Wattio Smart Home integration - el mensaje se produjo por primera vez a las 21:10:58 y aparece 17 veces

También lo he probado con "Warn" y no veo eventos.

Hasta hace poco estaba trabajando con la versión 2.3, con esta funcionaba correctamente, si lo necesitas te la puedo reenviar para que lo revises.

**Comment by GMTZMU** [comment]
Perdona, acabo de ver estos eventos.

Edit dmoranf: me copio los logs y edito el comentario para que no esté la info de tu instalación visible ;)

**Comment by dmoranf** [comment]
Prueba por favor con el debug puesto a darle a los switches de seguridad y ver que te dice el log, tienes que ver la solicitud del cambio de estado con la url de la Api y la respuesta.

Concretamente tendrías que buscar logs del tipo:

Sending ON request to SECURITY device ....

Sending OFF request to SECURITY device ....

Y las líneas siguientes donde aparecerá la url y el código de respuesta.

**Comment by GMTZMU** [comment]
Como debug no he visto ningún evento. Ahora lo tengo asi
logger:
  default: error
  logs:
    custom_components.wattio: debug

Y veo eventos de este tipo

Edit @dmoranf: 

2021-04-29 15:04:22 DEBUG (MainThread) [custom_components.wattio] https://api.wattio.com/public/v1/security/door/IEEE/off - Response Code:200

**Comment by dmoranf** [comment]
Hola!
Este es uno de los que buscaba:

2021-04-29 15:04:22 DEBUG (MainThread) [custom_components.wattio] https://api.wattio.com/public/v1/security/door/IEEE/off - Response Code:200

La cosa es que la API responde con un 200, por lo que debería de haber funcionado ... 

Voy a ver si puedo aumentar un poco el debug ya que veo la petición pero no se ve luego el estado desde Wattio, creo que esa parte la eliminé (el debug) sin querer en el último update.

Lo reviso 

Gracias!

**Comment by GMTZMU** [comment]
Gracias a ti.

Sent from Mail for Windows 10

**Comment by dmoranf** [comment]
Disculpa que he estado un poco a tope estos días ... esta semana retomamos sin falta :)

**Comment by GMTZMU** [comment]
Ok. No te preocupes. Genís MartinezEl 10 may. 2021 8:56, dmoranf ***@***.***> escribió:

Disculpa que he estado un poco a tope estos días ... esta semana retomamos sin falta :)

**Comment by dmoranf** [comment]
Hola,
He tenido algunos problemas para terminar de migrar la parte del registro que estaba dando problemas otra vez con la nueva versión.

He publicado lo que teníamos en la rama devel, junto con los cambios del registro y he metido un poco más de logging a los eventos de security.

Si actualizas a la rama principal (reinstala desde HACS si quieres que es más fácil), deberías ver entradas de log identificadas como SECURITY (texto en el log), tendríamos que ver un cambio de estado (que te devolverá 200), y a continuación, puede tardar, otra entrada que pondrá algo como Wattio SECURITY STATUS data: 

A ver qué reporta Wattio, la verdad es que he estado mirando un poco y me descoloca que respondan con un 200 y no se refleje el cambio ...

**Comment by GMTZMU** [comment]
Muy buenas, no sabia que estaba disponible en Hacs. Buen trabajo.

Lo he instalado desde Hacs, y con la configuración de logs siguiente:

# Debug Home Assistant
logger:
  default: error
  logs:
    custom_components.wattio: debug

Nada más reiniciar Hassio estos son los eventos.


** LOG EDITADO **



Sent from Mail for Windows 10

**Comment by dmoranf** [comment]
Si tienes acceso por consola, para filtrar el log a lo que nos interesa, desde la carpeta de home assistant, tienes que tener un homeassistant.log, puedes hacer un:

tail -f homeassistant.log | grep SECURITY

Déjalo corriendo y haz un cambio en un switch de seguridad, saldrá una entrada en el cambio del switch, déjalo corriendo unos 5 / 10 minutos, tendrías que ver las actualizaciones de estado de los elementos de seguridad.

Pásame el log que te da el comando si puedes y perdona por el mareo, pero es que no acabo de ver cuál es el problema, y en estos últimos logs no veo nada de los de seguridad :(

**Comment by dmoranf** [comment]
Perdona, acabo de darme cuenta que el motion y el door tienen modo de seguridad ... así que voy a hacer unas pruebas :)

**Comment by GMTZMU** [comment]
OkGenís MartinezEl 1 jun. 2021 15:09, dmoranf ***@***.***> escribió:

Perdona, acabo de darme cuenta que el motion y el door tienen modo de seguridad ... así que voy a hacer unas pruebas :)

**Comment by dmoranf** [comment]
Buenas,

He subido la versión 0.2.11, había un error en el cambio a async que he localizado al hacer yo las pruebas, he verificado que ya se actualiza el estado de los elementos de seguridad en Wattio y que al pulsar una acción está se refleja tanto en wattio como en el propio hass.

Creo que con esto debería de quedar funcionando como antes ...

**Comment by dmoranf** [comment]
Subida la versión 0.2.13 con el fix final, hay un bug (ya reportado) en la parte de la app de wattio con respecto al estado de los switches de seguridad, y a veces para que refresque el estado de los switches hay que cambiar de pestaña o reabrir la app, pero en principio las pruebas parecen correctas, hass es capaz de cambiar el estado y lo refleja aparentemente de forma correcta como lo hacía en versiones anteriores.

**Comment by GMTZMU** [comment]
Ya funciona. Al apagarlos dispositivos binarios se actualiza en wattio y viceversa, pero observo que tarda mucho tiempo.

Los he apagado en HASSIO, el primer dispositivo se ha actualizado en WATTIO pasados unas 12 minutos y el resto ha tardado un poco más.

Saludos.

Sent from Mail for Windows 10

**Comment by sarevol** [comment]
Buenos diad ya hace un monton de tiempo de vuestro foro,  pero solo necesito saber si WATTIO esta muerta definitiva mente ya que no me funciona nada de ellos desde febrero 2023. Nada se conecta ni da señales de vida; ni la central gate ni POD, ni sensor alguno, ni BAT, ni Thermic  y tampoco la App Wattiocam.    Al ver que en el pasado os funciono algo en la  integración, queria saber si debo tirar todo lo de WATTIO o se puede manipular y aprovechar. Actualmente tengo: 3 Gate, 4 BAT, 2 Thermic, 4 POD, 5 Camaras y algunos mas comprados a bajo coste en Leroy merlin que funcionaron hasta feb 2023.  Gracias y disculpad si este no es el foro adecuado.

**Comment by GMTZMU** [comment]
Muy buenas, a principios de mayo WATTIO cerro definitivamente y sus servidores estan apagados. La APP no te funcionará, ya que no se puede conectar a ningún servidor.
Internamente el GATE si que te funcionará y mediante la red zigbee conectará a todos los dispositivos internos, pero desconozco si las reglas que hubieses creado seguirán funcionando, pero no puedes añadir dispositivos, ni crear reglas desde el GATE.
Yo personalmente tenia una cámara conectada con Dropbox, después de haberse apagado los servidores, las reglas de WATTIO seguían funcionando y la cámara seguía enviando instantáneas a Dropbox.
Uno de los compañeros contacto con Patxi de WATTIO y le indico que el sistema estaba cifrado y no se podía liberar, ni integrar con ningún otro sistema, en mi caso estoy retirando poco a poco todos los elementos que tenia de WATTIO.
Saludos.
Genis Martinez


########################   

    En sábado, 8 de julio de 2023, 15:08:54 CEST, sarevol ***@***.***> escribió:  
 
 


Buenos diad ya hace un monton de tiempo de vuestro foro, pero solo necesito saber si WATTIO esta muerta definitiva mente ya que no me funciona nada de ellos desde febrero 2023. Nada se conecta ni da señales de vida; ni la central gate ni POD, ni sensor alguno, ni BAT, ni Thermic y tampoco la App Wattiocam. Al ver que en el pasado os funciono algo en la integración, queria saber si debo tirar todo lo de WATTIO o se puede manipular y aprovechar. Actualmente tengo: 3 Gate, 4 BAT, 2 Thermic, 4 POD, 5 Camaras y algunos mas comprados a bajo coste en Leroy merlin que funcionaron hasta feb 2023. Gracias y disculpad si este no es el foro adecuado.
